//  Copyright (c) 2014 Yellowbek Ltd. All rights reserved.

#import <OCMock/OCMock.h>

#import "FLTAsyncXCTestCase.h"
#import "FLTIntegration.h"

static NSString *BranchName = @"myBranch";
static NSString *ToPath = @"/path/to/clone";

@interface FLTIntegrationTests : FLTAsyncXCTestCase

@property (nonatomic, strong) FLTIntegration *integration;

@property (nonatomic, strong) id mockRepository;
@property (nonatomic, strong) id mockIntegrator;

@property (nonatomic, strong) NSURL *gitURL;

@end

@implementation FLTIntegrationTests

- (void)setUp {
    
    [super setUp];
    
    self.mockRepository = [OCMockObject niceMockForClass:[FLTRepository class]];
    
    self.mockIntegrator = [OCMockObject niceMockForClass:[FLTIntegrator class]];
    
    self.integration = [[FLTIntegration alloc] initWithIntegrator:self.mockIntegrator];

    self.gitURL = [NSURL URLWithString:@"/path/to/git/repo"];
}

- (void)testIntegrate_checksOutRepository {
    
    [[self.mockRepository expect] checkoutGitURL:self.gitURL branchName:BranchName toPath:ToPath completionHandler:[OCMArg any]];
    
    [self.integration integrateGitURL:self.gitURL branchName:BranchName toPath:ToPath repository:self.mockRepository completionHandler:nil];
    
    [self.mockRepository verify];
}

- (void)testIntegrate_afterCheckout_integratesWithConfiguration {
    
    __block FLTRepositoryCompletionHandler completionHandler;
    [[[self.mockRepository stub] andDo:^(NSInvocation *invocation) {
        FLTRepositoryCompletionHandler block;
        [invocation getArgument:&block atIndex:5];
        completionHandler = block;
    }] checkoutGitURL:self.gitURL branchName:BranchName toPath:ToPath completionHandler:[OCMArg any]];
    
    [self.integration integrateGitURL:self.gitURL branchName:BranchName toPath:ToPath repository:self.mockRepository completionHandler:nil];
    
    FLTIntegratorConfiguration *dummyConfiguration = [FLTIntegratorConfiguration new];

    [[self.mockIntegrator expect] integrateConfiguration:dummyConfiguration completionHandler:[OCMArg any]];
    
    completionHandler(dummyConfiguration);
    
    [self.mockIntegrator verify];
}

- (void)testIntegrate_afterIntegration_callsCompletionHandlerWithReport {
    
    __block FLTRepositoryCompletionHandler repositoryCompletionHandler;
    [[[self.mockRepository stub] andDo:^(NSInvocation *invocation) {
        FLTRepositoryCompletionHandler block;
        [invocation getArgument:&block atIndex:5];
        repositoryCompletionHandler = block;
    }] checkoutGitURL:self.gitURL branchName:BranchName toPath:ToPath completionHandler:[OCMArg any]];
    
    __block FLTIntegrationCompletionHandler integrationCompletionHandler;
    [[[self.mockIntegrator stub] andDo:^(NSInvocation *invocation) {
        FLTIntegrationCompletionHandler block;
        [invocation getArgument:&block atIndex:3];
        integrationCompletionHandler = block;
    }] integrateConfiguration:[OCMArg any] completionHandler:[OCMArg any]];
    
    FLTIntegrationReport *dummyReport = [FLTIntegrationReport new];
    
    [self.integration integrateGitURL:self.gitURL branchName:BranchName toPath:ToPath repository:self.mockRepository completionHandler:^(FLTIntegrationReport *report) {
        
        XCTAssertEqualObjects(dummyReport, report, @"Expected integration to pass report generated by integrator.");
    }];
    
    FLTIntegratorConfiguration *dummyConfiguration = [FLTIntegratorConfiguration new];
    
    repositoryCompletionHandler(dummyConfiguration);
    integrationCompletionHandler(dummyReport);
}

@end
